version: '3.8'

services:
  nodepulse:
    build: .
    container_name: nodepulse
    expose:
      - 3000
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - PORT=3000
    networks:
      - sentnl-net
    restart: unless-stopped

networks:
  sentnl-net:
    external: true 